# Generated by Django 3.2 on 2021-04-13 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SqurInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_squirrel_id', models.CharField(max_length=20)),
                ('latitude', models.CharField(max_length=50)),
                ('longitude', models.CharField(max_length=50)),
                ('shift', models.CharField(choices=[('AM', 'AM'), ('PM', 'PM')], default='Unknown', max_length=2)),
                ('date', models.DateField(max_length=10)),
                ('age', models.CharField(choices=[('Adult', 'Adult'), ('Juvenile', 'Juvenile'), ('Unknown', 'Unknown')], default='Unknown', max_length=20)),
                ('primary_fur_color', models.CharField(choices=[('Cinnamon', 'Cinnamon'), ('Black', 'Black'), ('Gray', 'Gray'), ('Unknown', 'Unknown')], default='Unknown', max_length=20)),
                ('location', models.CharField(choices=[('Above Ground', 'Above Ground'), ('Ground Plane', 'Ground Plane'), ('Unknown', 'Unknown')], default='Unknown', max_length=20)),
                ('specific_location', models.CharField(blank=True, max_length=200)),
                ('running', models.BooleanField(default=False, help_text='Squirrel was seen running.')),
                ('chasing', models.BooleanField(default=False, help_text='Squirrel was seen chasing.')),
                ('climbing', models.BooleanField(default=False, help_text='Squirrel was seen climbing.')),
                ('eating', models.BooleanField(default=False, help_text='Squirrel was seen eating.')),
                ('foraging', models.BooleanField(default=False, help_text='Squirrel was seen foraging.')),
                ('other_activities', models.CharField(blank=True, max_length=200)),
                ('kuks', models.BooleanField(default=False, help_text='Squirrel was heard kukking.')),
                ('quaas', models.BooleanField(default=False, help_text='Squirrel was heard quaaing.')),
                ('moans', models.BooleanField(default=False, help_text='Squirrel was heard moaning.')),
                ('tail_flags', models.BooleanField(default=False, help_text='Squirrel was seen flagging its tail.')),
                ('tail_twitches', models.BooleanField(default=False, help_text='Squirrel was seen twitching its tail.')),
                ('approaches', models.BooleanField(default=False, help_text='Squirrel was seen approaching human, seeking food.')),
                ('indifferent', models.BooleanField(default=False, help_text='Squirrel was indifferent to human presence.')),
                ('runs_from', models.BooleanField(default=False, help_text='Squirrel was running from humans, seeing them as a threat.')),
            ],
        ),
    ]
